name: Sync Fork

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: tgymnich/fork-sync@v1.2
        with:
          token: ${{ secrets.PAT }}
          owner: anuraghazra
          head: master
          base: master
